CREATE TABLE arrests.arrest (
arrest_rec_num int primary key,
bin int,
pcn text,
citation_num text,
sid text,
last_name text,
first_name text,
middle_name text,
suffix_name text,
moniker text,
arrest_date date,
offense_date date,
date_to_appear date,
crime_county text,
palm text,
treat_as_adult text,
aoi text,
boi text,
agency_case_num text,
fingerprint_status text,
entering_agency text,
court_docket text
)
