CREATE TABLE warrants.warrant_update (
warrant_rec_num int primary key,
bin int,
nin int, --REFERENCES warrants.base (nin),
last_name text,
first_name text,
middle_name text,
suffix_name text,
moniker text,
cert_as_adult_flag text,
warrant_date text,
expiration_date text,
failure_to_flag text,
traffic_violation_flag text,
day_service_only_flag text,
requesting_ori text,
orig_agency_case_num text,
court_ori text,
court_case_num text,
prosecutor_ori text,
prosecutor_num text,
transporting_ori text,
transportation_code text, --REFERENCES warrants.transportationcode (transportation_code),
packing_ori text,
confirming_ori text,
tot_cash_bail money,
tot_surety_bail money,
no_or_bail_flag text,
no_bail_flag text,
bail_comment text,
linking_ori text,
linking_oca text,
arresting_ori text,
miscellaneous text,
entering_agency_ori text,
retake_warrant text,
local_warrant_num text,
tot_converted_bail_amount text
)
